apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: qts3q0g7j-go-gitops
  description: This is GitOps manifest for qts3q0g7j-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=qts3q0g7j-go
    backstage.io/kubernetes-id: qts3q0g7j-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: qts3q0g7j-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:qts3q0g7j-go
