apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qts3q0g7j-go
  janus-idp.io/tekton: qts3q0g7j-go
  backstage.io/kubernetes-id: qts3q0g7j-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qts3q0g7j-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
